"""
LOOP-05 — Game Loop.

Produces a real Godot 4 project on disk at `workspace/games/<slug>/` with
a runnable main scene. The operator opens the folder in the Godot editor
and hits F5 to run it.

This is a scaffold, not a finished game. The LLM fills in the GDScript
for game mechanics. Assets are placeholder — Blender integration for
real models happens when the WORKSTATION tier has an MCP Blender server
running (see mcp_servers/blender_server.py).

WORKSTATION tier required (enforced by echo_core before calling run).
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from compliance.legal_gate import LegalGate, Jurisdiction
from intel.perplexity_client import PerplexityIntelClient
from loops._base import LoopBase
from util.logging_setup import get_logger

log = get_logger("echo.loop.game")


PROJECT_GODOT_TEMPLATE = """; Engine configuration file.
; Generated by Echo-Orchestra.

config_version=5

[application]

config/name="%NAME%"
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.2", "Forward Plus")
config/icon="res://icon.svg"

[rendering]

renderer/rendering_method="forward_plus"
"""

MAIN_TSCN_TEMPLATE = """[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://main.gd" id="1"]

[node name="Main" type="Node2D"]
script = ExtResource("1")

[node name="Label" type="Label" parent="."]
offset_left = 32.0
offset_top = 32.0
offset_right = 400.0
offset_bottom = 80.0
text = "%NAME%"

[node name="Hint" type="Label" parent="."]
offset_left = 32.0
offset_top = 96.0
offset_right = 600.0
offset_bottom = 128.0
text = "Press SPACE to start"
"""

MAIN_GD_FALLBACK = """extends Node2D

var score: int = 0

func _ready() -> void:
    print("%NAME% loaded")

func _input(event: InputEvent) -> void:
    if event.is_action_pressed("ui_accept"):
        score += 1
        $Label.text = "%NAME% — score: " + str(score)
"""

ICON_SVG = """<?xml version="1.0" encoding="UTF-8"?>
<svg width="128" height="128" viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg">
  <rect width="128" height="128" fill="#478cbf"/>
  <text x="64" y="80" text-anchor="middle" fill="white" font-family="Arial" font-size="48" font-weight="bold">E</text>
</svg>
"""


class GameLoop(LoopBase):
    loop_name = "game"
    minimum_tier = "workstation"

    def __init__(self, output_root: str = "workspace/games"):
        super().__init__()
        self.gate = LegalGate()
        self.intel = PerplexityIntelClient()
        self.output_root = Path(output_root)
        self.output_root.mkdir(parents=True, exist_ok=True)

    def run(self, prompt: str, genre: str = "arcade") -> dict:
        log.info("GameLoop start: prompt=%s genre=%s", prompt, genre)

        # Research
        self._record("sonar-pro", "research", 400, 1000, agent="echo_intel")
        try:
            research = self.intel.research_product_idea(prompt, f"indie {genre} game")
        except Exception as exc:
            return {"status": "blocked", "reason": f"research_failed: {exc}"}

        compliance = self.gate.check(
            product_type="game",
            target_markets=[Jurisdiction.US, Jurisdiction.EU],
            description=prompt,
        )
        if not compliance.approved:
            return {"status": "blocked", "reason": compliance.block_reason}

        # Design doc
        self._record("claude-opus-4-7", "design", 1200, 2000, agent="designer")
        design = self._call_model(
            "premium-code",
            prompt=(
                f"Write a concise game design document for: {prompt}. "
                f"Genre: {genre}. Include: core loop, controls, 3 levels, "
                f"win condition, lose condition. Keep it under 600 words."
            ),
            max_tokens=2000,
        ) or f"A {genre} game about {prompt}."

        # Generate GDScript
        self._record("claude-opus-4-7", "code", 2500, 4000, agent="coder")
        gd_code = self._call_model(
            "premium-code",
            prompt=(
                f"Write complete GDScript 2.x (Godot 4) for the main scene of "
                f"this game. Extend Node2D. Implement the core loop from this "
                f"design:\n\n{design}\n\n"
                f"Assume a $Label and $Hint Label node exist. Do not reference "
                f"any external assets. Return only valid GDScript — no markdown "
                f"fences, no commentary."
            ),
            system="You write clean GDScript that compiles in Godot 4.2.",
            max_tokens=3000,
        )

        # Name
        slug = self.slug(prompt)[:40] or "echo-game"
        name = prompt[:40]

        # Write project
        proj_dir = self.output_root / slug
        if proj_dir.exists():
            return {"status": "exists", "output_path": str(proj_dir)}
        proj_dir.mkdir(parents=True, exist_ok=True)

        (proj_dir / "project.godot").write_text(
            PROJECT_GODOT_TEMPLATE.replace("%NAME%", name), encoding="utf-8")
        (proj_dir / "main.tscn").write_text(
            MAIN_TSCN_TEMPLATE.replace("%NAME%", name), encoding="utf-8")
        # If the LLM failed, use fallback
        if not gd_code or "extends" not in gd_code.lower():
            gd_code = MAIN_GD_FALLBACK.replace("%NAME%", name)
        (proj_dir / "main.gd").write_text(gd_code, encoding="utf-8")
        (proj_dir / "icon.svg").write_text(ICON_SVG, encoding="utf-8")
        (proj_dir / "design.md").write_text(design, encoding="utf-8")
        (proj_dir / "meta.json").write_text(json.dumps({
            "name": name, "slug": slug, "genre": genre, "prompt": prompt,
            "created_at": datetime.utcnow().isoformat(),
            "engine": "godot-4.2",
            "disclosures": compliance.required_disclosures,
            "next_steps": [
                f"Open {proj_dir} in Godot 4.2",
                "Press F5 to run",
                "Replace placeholder labels with real assets",
            ],
        }, indent=2), encoding="utf-8")

        log.info("GameLoop wrote %s", proj_dir)
        return {
            "status": "created",
            "output_path": str(proj_dir),
            "engine": "godot-4.2",
            "next_steps": [f"Open {proj_dir} in Godot 4.2 and press F5"],
        }
