"""
Legal / compliance gate.

Previous version did `if any(cat in description.lower() for cat in PROHIBITED_CATEGORIES)`
where cat was something like 'social_scoring' — that substring almost never appears
in a natural product description, so the gate approved nearly everything.

This version uses per-category keyword lists that match natural language, plus a
confidence score. An optional LLM adjudication hook is exposed for callers that
want stronger gating for edge cases.

This is not legal counsel. It is a filter. The operator bears full responsibility.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Callable, List, Optional

from util.logging_setup import get_logger

log = get_logger("echo.legal")


class RiskLevel(Enum):
    PROHIBITED = "prohibited"
    HIGH_RISK = "high_risk"
    LIMITED_RISK = "limited_risk"
    MINIMAL_RISK = "minimal_risk"


class Jurisdiction(Enum):
    EU = "eu"
    US = "us"
    BOTH = "both"
    OTHER = "other"


@dataclass
class ComplianceResult:
    approved: bool
    risk_level: RiskLevel
    required_disclosures: List[str] = field(default_factory=list)
    required_actions: List[str] = field(default_factory=list)
    matched_categories: List[str] = field(default_factory=list)
    block_reason: Optional[str] = None
    max_penalty_eur: float = 0.0
    max_penalty_usd: float = 0.0


# EU AI Act Article 5 prohibited categories, phrased as actual product descriptions
PROHIBITED_KEYWORDS = {
    "social_scoring": [
        "social credit", "social scoring", "citizen score", "behavior score",
        "trustworthiness rank", "lifestyle rating",
    ],
    "manipulative_subliminal": [
        "subliminal", "manipulate users without consent",
        "deceptive technique", "covertly influence",
    ],
    "exploitation_vulnerable": [
        "target children to purchase", "exploit elderly", "target disabled",
        "prey on addiction", "exploit cognitive impairment",
    ],
    "biometric_public": [
        "real-time facial recognition in public", "public biometric surveillance",
        "mass facial recognition", "public-space identification",
    ],
    "emotion_recognition_work_edu": [
        "emotion recognition at work", "emotion detection in classroom",
        "student emotion monitoring", "employee mood surveillance",
    ],
    "untargeted_face_scraping": [
        "scrape faces", "untargeted facial scraping", "mass image scraping for recognition",
    ],
    "predictive_policing": [
        "predictive policing", "crime prediction by individual",
        "pre-crime scoring",
    ],
    "personality_risk_assessment": [
        "personality-based risk scoring", "criminal personality prediction",
    ],
}

# EU AI Act Annex III high-risk categories
HIGH_RISK_KEYWORDS = {
    "credit_scoring": ["credit score", "creditworthiness", "loan approval AI", "lending decision AI"],
    "employment_recruitment": ["resume screening", "candidate ranking", "hiring decision", "automated interview scoring"],
    "education_admissions": ["admissions decision", "student evaluation AI", "automated grading for admission"],
    "law_enforcement": ["law enforcement decision", "police risk assessment"],
    "migration_asylum": ["asylum decision", "visa risk scoring", "border screening AI"],
    "justice_democratic": ["judicial decision AI", "election influence", "voter targeting at scale"],
    "critical_infrastructure": ["power grid control", "water system control", "traffic control AI"],
    "healthcare_diagnosis": ["medical diagnosis", "clinical decision support", "automated triage"],
    "biometric_id": ["biometric identification", "fingerprint matching system"],
}

# US FTC / sectoral high-risk
FTC_HIGH_RISK_KEYWORDS = {
    "financial_services": ["investment advice", "trading bot", "portfolio management", "financial advisor AI"],
    "health_wellness": ["health advice", "medical advice", "diagnose", "treatment recommendation"],
    "legal_services": ["legal advice", "legal representation", "contract review for court"],
    "cryptocurrency": ["crypto trading", "token launch", "defi protocol"],
    "alcohol_tobacco": ["alcohol sales", "tobacco sales", "vape marketplace"],
    "real_estate": ["property valuation", "mortgage approval", "rental screening"],
}

DISCLOSURE_TEMPLATES = {
    "ai_generated": "This product was created with AI assistance.",
    "ai_content": "This content was generated by artificial intelligence.",
    "not_legal_advice": "This is not legal, financial, or medical advice. Consult a qualified professional.",
    "not_guaranteed": "Results are not guaranteed. Past performance does not indicate future results.",
    "eu_compliant": "This AI system is designed to comply with EU AI Act transparency requirements.",
}

LLMAdjudicator = Callable[[str, List[str]], bool]
"""Optional hook: (description, matched_categories) -> is_actually_prohibited."""


class LegalGate:
    """Pre-synthesis compliance filter. Runs BEFORE any build."""

    def __init__(self, adjudicator: Optional[LLMAdjudicator] = None):
        self._adjudicator = adjudicator

    @staticmethod
    def _scan(description: str, category_map: dict) -> List[str]:
        desc_lower = description.lower()
        hits = []
        for category, keywords in category_map.items():
            for kw in keywords:
                if kw in desc_lower:
                    hits.append(category)
                    break
        return hits

    def check(
        self,
        product_type: str,
        target_markets: List[Jurisdiction],
        description: str,
        has_financial_component: bool = False,
    ) -> ComplianceResult:
        prohibited_hits = self._scan(description, PROHIBITED_KEYWORDS)
        eu_high_risk_hits = self._scan(description, HIGH_RISK_KEYWORDS)
        ftc_high_risk_hits = []
        if product_type and product_type.lower() in FTC_HIGH_RISK_KEYWORDS:
            ftc_high_risk_hits.append(product_type.lower())
        ftc_desc_hits = self._scan(description, FTC_HIGH_RISK_KEYWORDS)
        ftc_high_risk_hits.extend(ftc_desc_hits)

        # PROHIBITED -> block
        if prohibited_hits:
            # Optional LLM second-pass. If provided and it says "not actually prohibited",
            # downgrade to HIGH_RISK rather than PROHIBITED.
            if self._adjudicator and not self._adjudicator(description, prohibited_hits):
                log.info(
                    "Adjudicator downgraded %s to high-risk for: %s",
                    prohibited_hits, description[:100],
                )
                eu_high_risk_hits.extend(prohibited_hits)
                prohibited_hits = []
            else:
                return ComplianceResult(
                    approved=False,
                    risk_level=RiskLevel.PROHIBITED,
                    matched_categories=prohibited_hits,
                    block_reason=f"Matches EU AI Act prohibited practices (Article 5): {prohibited_hits}",
                    max_penalty_eur=35_000_000,
                    max_penalty_usd=38_000_000,
                )

        disclosures: List[str] = []
        actions: List[str] = []
        risk = RiskLevel.MINIMAL_RISK

        if eu_high_risk_hits:
            risk = RiskLevel.HIGH_RISK
            actions += [
                "EU conformity assessment required before market entry",
                "CE marking required",
                "EU database registration required",
                "Human oversight mechanism required",
            ]
            disclosures.append(DISCLOSURE_TEMPLATES["eu_compliant"])

        if Jurisdiction.EU in target_markets or Jurisdiction.BOTH in target_markets:
            disclosures.append(DISCLOSURE_TEMPLATES["ai_generated"])
            disclosures.append(DISCLOSURE_TEMPLATES["eu_compliant"])
            if risk == RiskLevel.MINIMAL_RISK:
                risk = RiskLevel.LIMITED_RISK

        if Jurisdiction.US in target_markets or Jurisdiction.BOTH in target_markets:
            disclosures.append(DISCLOSURE_TEMPLATES["ai_content"])
            if ftc_high_risk_hits:
                actions += [
                    "FTC compliance review required",
                    "Claim substantiation documentation required",
                ]
                if risk == RiskLevel.MINIMAL_RISK or risk == RiskLevel.LIMITED_RISK:
                    risk = RiskLevel.HIGH_RISK

        if has_financial_component:
            actions += [
                "Financial services AI risk assessment required (Treasury FS AI RMF)",
                "SEC/CFTC compliance verification required",
                "Max 5% treasury allocation to speculative instruments (hard cap in ledger)",
            ]
            disclosures.append(DISCLOSURE_TEMPLATES["not_guaranteed"])

        actions += [
            "Monitor transaction volume for KYC/KYB triggers",
            "EU: report to tax authorities if >€2,000 or 30 transactions (DAC7)",
            "US: verify identity if >200 transactions or $5,000 (INFORM Act)",
        ]
        disclosures.append(DISCLOSURE_TEMPLATES["not_legal_advice"])

        max_eur = 15_000_000 if risk == RiskLevel.HIGH_RISK else 7_500_000
        max_usd = 16_000_000 if risk == RiskLevel.HIGH_RISK else 8_000_000

        return ComplianceResult(
            approved=True,
            risk_level=risk,
            required_disclosures=sorted(set(disclosures)),
            required_actions=actions,
            matched_categories=sorted(set(eu_high_risk_hits + ftc_high_risk_hits)),
            max_penalty_eur=max_eur,
            max_penalty_usd=max_usd,
        )
